language: node_js
node_js:
- node
cache:
  yarn: true
addons:
  code_climate:
    repo_token: 9ab5191ff81e1aaab31d29f093f64827f9cbd8302c1f4cdcfe4a2c67d826c58c
  firefox: latest
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- $(npm bin)/flow check
- $(npm bin)/eslint src/textcomplete.codemirror.js test/**/*.js
- $(npm bin)/karma start --single-run --browsers Firefox
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/*/lcov.info
notifications:
  email: false
